// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABzlpKIZ8ub53qb3wcMxBgYPh2fQ3ICeg',
    appId: '1:908952546482:web:1bbdd6659455b339b12dab',
    messagingSenderId: '908952546482',
    projectId: 'instax-44100',
    authDomain: 'instax-44100.firebaseapp.com',
    storageBucket: 'instax-44100.appspot.com',
    measurementId: 'G-Y1GJJWM2PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo6HTCdidiQcesn8MsrtS_VOasvEPaweM',
    appId: '1:908952546482:android:e82594bf2e5c1d81b12dab',
    messagingSenderId: '908952546482',
    projectId: 'instax-44100',
    storageBucket: 'instax-44100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb8fjwLmR-QBsEROKbugdeejXXlNGvm8Y',
    appId: '1:908952546482:ios:d860a0a5eb85f331b12dab',
    messagingSenderId: '908952546482',
    projectId: 'instax-44100',
    storageBucket: 'instax-44100.appspot.com',
    iosBundleId: 'com.example.instax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb8fjwLmR-QBsEROKbugdeejXXlNGvm8Y',
    appId: '1:908952546482:ios:d860a0a5eb85f331b12dab',
    messagingSenderId: '908952546482',
    projectId: 'instax-44100',
    storageBucket: 'instax-44100.appspot.com',
    iosBundleId: 'com.example.instax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABzlpKIZ8ub53qb3wcMxBgYPh2fQ3ICeg',
    appId: '1:908952546482:web:adbfff2144a7e19db12dab',
    messagingSenderId: '908952546482',
    projectId: 'instax-44100',
    authDomain: 'instax-44100.firebaseapp.com',
    storageBucket: 'instax-44100.appspot.com',
    measurementId: 'G-VTDCTJL9XD',
  );
}
